import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    
container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
  },
   header: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#fff',
    
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  headerTitle: {
    fontSize: 24,
    marginLeft: 12,
    fontWeight: 'bold',
    color: '#101828',
  },
  imageSection: {
    alignItems: 'center',
    marginVertical: 20,
  },
  avatarWrapper: {
    position: 'relative',
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 60,
    borderColor: '#F3F4F6',
    borderWidth: 2,
},
  cameraButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#009966',
    padding: 6,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#F3F4F6',
  },
  changePhotoText: {
    marginTop: 10,
    color: '#009966',
    fontWeight: '600',
  },
  card: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    padding: 16,
    borderRadius: 16,
    marginBottom: 5,
    marginTop: 20,
  },
  label: {
    fontSize: 12,
    color: '#6A7282',
    marginTop: 25,
  },
  input: {
    fontSize: 15,
    color: '#1018287b',
    fontWeight: '500',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#eeeeee7b',
  },
  currencyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  currencyText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#101828',
  },
  saveButton: {
    backgroundColor: '#009966',
    margin: 20,
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 1,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  successToast: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 20,
    marginTop: -6,
    marginBottom: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  successToastText: {
    color: '#166534',
    fontWeight: '600',
  },
  logoutButton: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: 20,
    marginTop: 16,
    elevation: 1,
  },
  logoutText: {
    color: '#ff2056',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  currencyItem: {
    paddingVertical: 14,
  },
  currencyItemText: {
    fontSize: 16,
  },
  cancelButton: {
    backgroundColor: '#f9f7f7',
    marginHorizontal: 3,
    padding: 20,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: 20,
    marginTop: 16,
    elevation: 2,
  },
settingsCard: {
  backgroundColor: '#FFFFFF',
  marginHorizontal: 20,
  marginTop: 5,
  borderRadius: 20,
  overflow: 'hidden',
  borderWidth: 1,
  borderColor: '#F3F4F6',
},

settingsRow: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 18,
  paddingHorizontal: 16,
},

iconWrapper: {
  width: 44,
  height: 44,
  borderRadius: 14,
  backgroundColor: '#F3F4F6',
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 14,
},

settingsText: {
  flex: 1,
  fontSize: 16,
  fontWeight: '700',
  color: '#101828',
  fontFamily: 'Inter',
},

divider: {
  height: 1,
  backgroundColor: '#F3F4F6',
},

versionContainer: {
  alignItems: 'center',
  padding: 8,
  marginBottom: 20,
},
versionText: {
  color: '#99A1AF',
  fontSize: 12,
  fontFamily: 'Inter-regular',
},
currencyModalHeader: {
  alignItems: 'center',
  marginBottom: 16,
},
currencyModalIconCircle: {
  width: 56,
  height: 56,
  borderRadius: 28,
  backgroundColor: '#ECFDF5',
  alignItems: 'center',
  justifyContent: 'center',
  marginBottom: 12,
  borderWidth: 1,
  borderColor: '#D1FAE5',
},
currencyModalSubtitle: {
  marginTop: 6,
  fontSize: 13,
  lineHeight: 18,
  color: '#6B7280',
  textAlign: 'center',
},
currencyModalCurrentBadge: {
  marginTop: 14,
  width: '100%',
  backgroundColor: '#F9FAFB',
  borderWidth: 1,
  borderColor: '#E5E7EB',
  borderRadius: 16,
  paddingVertical: 12,
  paddingHorizontal: 14,
  alignItems: 'center',
},
currencyModalCurrentBadgeLabel: {
  fontSize: 11,
  fontWeight: '700',
  color: '#6B7280',
  textTransform: 'uppercase',
  letterSpacing: 0.6,
  marginBottom: 4,
},
currencyModalCurrentBadgeValue: {
  fontSize: 14,
  fontWeight: '700',
  color: '#101828',
  textAlign: 'center',
},
currencyModalList: {
  paddingBottom: 12,
},
currencyCardModal: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#F9FAFB',
  padding: 14,
  borderRadius: 18,
  marginBottom: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
},
selectedCurrencyCardModal: {
  backgroundColor: '#ECFDF5',
  borderWidth: 1.5,
  borderColor: '#009966',
  shadowColor: '#009966',
  shadowOpacity: 0.08,
  shadowOffset: { width: 0, height: 6 },
  shadowRadius: 12,
  elevation: 2,
},
symbolWrapperModal: {
  width: 44,
  height: 44,
  borderRadius: 22,
  backgroundColor: '#FFFFFF',
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 14,
  borderWidth: 1,
  borderColor: '#E5E7EB',
},
symbolTextModal: {
  fontSize: 18,
  fontWeight: '600',
  color: '#111827',
},
currencyTextModal: {
  fontSize: 15,
  fontWeight: '700',
  color: '#111827',
},

currencyModalItemMeta: {
  flex: 1,
},

currencyModalItemName: {
  marginTop: 2,
  fontSize: 13,
  color: '#6B7280',
},

selectedCurrencyTextModal: {
  color: '#009966',
},

checkWrapperModal: {
  width: 26,
  height: 26,
  borderRadius: 13,
  backgroundColor: '#009966',
  justifyContent: 'center',
  alignItems: 'center',
},
currencyModalSelectedPill: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
  backgroundColor: '#009966',
  paddingVertical: 8,
  paddingHorizontal: 10,
  borderRadius: 999,
},
currencyModalSelectedPillText: {
  color: '#FFFFFF',
  fontSize: 12,
  fontWeight: '700',
},
currencyModalDoneButton: {
  backgroundColor: '#009966',
  padding: 14,
  borderRadius: 14,
  alignItems: 'center',
  marginTop: 4,
  elevation: 1,
},
currencyModalDoneButtonText: {
  color: '#fff',
  fontWeight: '700',
  fontSize: 15,
},
  deleteButton: {
    backgroundColor: '#FEEAEA',
    marginHorizontal: 20,
    padding: 17,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
    elevation: 1,
  },
  deleteButtonDisabled: {
    opacity: 0.6,
  },
  deleteButtonText: {
    color: '#ff2056',
    fontWeight: '700',
  },
  deleteModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    maxHeight: '90%',
  },
  deleteModalHeader: {
    alignItems: 'center',
    marginBottom: 18,
    position: 'relative',
  },
  deleteIconCircle: {
    width: 60,
    height: 60,
    backgroundColor: '#FEE2E2',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  deleteModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  deleteCloseButton: {
    position: 'absolute',
    top: -10,
    right: 0,
    padding: 8,
  },
  deleteModalScroll: {
    maxHeight: 330,
    marginBottom: 16,
  },
  deleteModalBody: {
    paddingRight: 8,
  },
  deleteModalText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 14,
    textAlign: 'center'
  },
  deleteSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#101828',
    marginBottom: 12,
  },
  deleteListItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  deleteListBullet: {
    color: '#DC2626',
    fontSize: 14,
    marginRight: 8,
    marginTop: 2,
    fontWeight: '700',
  },
  deleteListText: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  deleteWarningText: {
    marginTop: 8,
    fontSize: 13,
    color: '#B91C1C',
    fontWeight: '600',
  },
  notificationModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    maxHeight: '90%',
  },
  notificationModalHeader: {
    alignItems: 'center',
    marginBottom: 18,
    position: 'relative',
  },
  notificationIconCircle: {
    width: 60,
    height: 60,
    backgroundColor: '#CCFBF1',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  notificationModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  notificationCloseButton: {
    position: 'absolute',
    top: -10,
    right: 0,
    padding: 8,
  },
  notificationModalBody: {
    paddingRight: 8,
    paddingLeft: 2,
  },
  notificationModalText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  notificationFeatureCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  notificationFeatureDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0F766E',
    marginTop: 5,
    marginRight: 12,
  },
  notificationFeatureDotSoon: {
    backgroundColor: '#F59E0B',
  },
  notificationFeatureTextWrap: {
    flex: 1,
  },
  notificationFeatureTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#101828',
    marginBottom: 4,
  },
  notificationFeatureText: {
    fontSize: 13,
    color: '#475467',
    lineHeight: 19,
  },
  notificationFooterText: {
    marginTop: 8,
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 19,
  },
  notificationDoneButton: {
    marginTop: 6,
    backgroundColor: '#0F766E',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 1,
  },
  notificationDoneButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  helpModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    maxHeight: '90%',
  },
  helpModalHeader: {
    alignItems: 'center',
    marginBottom: 18,
    position: 'relative',
  },
  helpIconCircle: {
    width: 60,
    height: 60,
    backgroundColor: '#D1FAE5',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  helpModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  helpCloseButton: {
    position: 'absolute',
    top: -10,
    right: 0,
    padding: 8,
  },
  helpModalScroll: {
    maxHeight: 340,
    marginBottom: 8,
  },
  helpModalBody: {
    paddingRight: 8,
    paddingLeft: 2,
  },
  helpModalText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  helpInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
  },
  helpInfoText: {
    flex: 1,
    marginLeft: 12,
  },
  helpLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#047857',
    marginBottom: 4,
  },
  helpValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  helpCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  helpCopiedText: {
    color: '#059669',
    fontSize: 12,
    fontWeight: '700',
  },
  helpSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#101828',
    marginBottom: 12,
  },
  helpFeatureCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  helpFeatureDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#059669',
    marginTop: 5,
    marginRight: 12,
  },
  helpFeatureDotAccent: {
    backgroundColor: '#0F766E',
  },
  helpFeatureDotSoon: {
    backgroundColor: '#10B981',
  },
  helpFeatureTextWrap: {
    flex: 1,
  },
  helpFeatureTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#101828',
    marginBottom: 4,
  },
  helpFeatureText: {
    fontSize: 13,
    color: '#475467',
    lineHeight: 19,
  },
  helpFooterText: {
    marginTop: 8,
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 19,
  },
  helpDoneButton: {
    marginTop: 6,
    backgroundColor: '#059669',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 1,
  },
  helpDoneButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  preferencesModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    maxHeight: '90%',
  },
  preferencesModalHeader: {
    alignItems: 'center',
    marginBottom: 18,
    position: 'relative',
  },
  preferencesIconCircle: {
    width: 60,
    height: 60,
    backgroundColor: '#D1FAE5',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  preferencesModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  preferencesCloseButton: {
    position: 'absolute',
    top: -10,
    right: 0,
    padding: 8,
  },
  preferencesModalBody: {
    paddingRight: 8,
    paddingLeft: 2,
  },
  preferencesModalText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  preferencesFeatureCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  preferencesFeatureDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#047857',
    marginTop: 5,
    marginRight: 12,
  },
  preferencesFeatureDotSoon: {
    backgroundColor: '#10B981',
  },
  preferencesFeatureTextWrap: {
    flex: 1,
  },
  preferencesFeatureTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#101828',
    marginBottom: 4,
  },
  preferencesFeatureText: {
    fontSize: 13,
    color: '#475467',
    lineHeight: 19,
  },
  preferencesFooterText: {
    marginTop: 8,
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 19,
  },
  preferencesDoneButton: {
    marginTop: 6,
    backgroundColor: '#047857',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 1,
  },
  preferencesDoneButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  dangerButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  dangerCancelButton: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 1,
  },
  dangerConfirmButton: {
    flex: 1,
    backgroundColor: '#DC2626',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    elevation: 1,
  },
});